from enum import Enum


class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    DROP_INVENTORY = 5
    TARGETING = 6
    LEVEL_UP = 7
    CHARACTER_SCREEN = 8
    CHARACTER_CREATION = 9
    GENDER_SELECTION = 10
    JOB_SELECTION = 11
    SKILL_SELECTION = 12
    SHOW_SKILL_MENU = 13
    SKILL_TARGETING = 13
